config/routes.rb
Rails.application.routes.draw do 
  resources :events

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

    def index
      @events = Event.all
    end

    def show
    end

    def new
      @event = Event.new
    end

    def edit
    end

    def create
      @event = Event.new(event_params)

      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @event.update(event_params)
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

      def set_event
        @event = Event.find(params[:id])
      end

      def event_params
        params.require(:event).permit(:title, :description)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @events = Event.all
    @days = %w[Mon Tue Wed Thu Fri]
    @time = "8:00am - 3:00pm"
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def active? path
  "active" if current_page? path
 end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/index.html.erb
<%= @events.each do |event| %>

  <%= link_to event.name, event_path(event) %>

<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p><%= @event.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>MomsSite</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


  </head>

  <body>
    <%= render './shared/navbar' %>
    <%= yield %>
    <%= render './shared/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>After Mothering 6 kids and working as a teachers aid for many years, I have decided to help parents get some much needed me time</p>

app/views/pages/contact.html.erb
<div class="container">
	<div class="row contact">
		<h1 class="page-title" >Contact</h1>
    <div class="col m6">
      <p>Call us with questions at (435) 650-9773</p>
    </div>

    <div class="col m6">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3074.242326693723!2d-110.79653839454456!3d39.599223316819696!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x874eb943460b3837%3A0x4125350828ad5089!2s1181+E+Main+St%2C+Price%2C+UT+84501!5e0!3m2!1sen!2sus!4v1498522584799" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
  </head>

  <body>


    <div class="container">
      <div class="row">
        <%= render  'shared/calendar' %>
        <%= render 'shared/sidebar' %>
      </div>
    </div>

app/views/shared/_calendar.html.erb
<div>
	<div class="col m8">
	  <div class="card">
      <div class="card-content custom-card">
				<div class="calendar">
					<ul class="collapsible" data-collapsible="accordion">
						<li>
							<div class="collapisble-header">Calendar</div>
							<div class="collapsible-body">
							<iframe  src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;wkst=1&amp;bgcolor=%23edecda&amp;src=q5mvn0av2obfglmmlhq56di56k%40group.calendar.google.com&amp;color=%2323164E&amp;src=juhun4fnhdvt8lvhon5a8n9flk%40group.calendar.google.com&amp;color=%23AB8B00&amp;ctz=America%2FDenver" style="border-width:0" width="100%" height="100%" frameborder="0" scrolling="yes"></iframe>
							</div>
						</li>
					</ul>
				</div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_events.html.erb
<div class="card sidebar-card event-sidebar">
  <h4>Events</h4>
  <ul>
    <% @events.each do |event| %>
      <li><%= link_to event.title, event_path(event) %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_footer.html.erb
<footer id="footer" class="light-blue lighten-1">
	<p> Built by me</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="light-blue lighten-1" role="navigation">
  <div class="container">
    <div class="nav-wrapper ">
      <%= link_to (image_tag "logo.svg", height: '50px', class: 'nav-img' ), root_path, id: 'logo-container', class: 'logo'%>
      <a data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li class="custom-nav"><%= link_to 'About Us', about_path, class: active?(about_path) %></li>
        <li class="custom-nav"><%= link_to 'Contact', contact_path, class: active?(contact_path) %></li>
      </ul>
      <ul class="side-nav light-blue lighten-1" id="mobile">
        <li class="custom-nav"><%= link_to 'About Us', about_path %></li>
        <li class="custom-nav"><%= link_to 'Contact', contact_path%></li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_schedule.html.erb
<div class="card sidebar-card schedule">
  <h4>Schedule</h4>
  <ul>
    <% @days.each do |open| %>
      <li><%= open %>: <span class="right-align"><%= @time %></span> </li>
    <% end %>
  </ul>
</div>

app/views/shared/_sidebar.html.erb
<div class="side col m3 ">
  <div class="card sidebar-card">
    <h4>About</h4>
    <p>We are a family friendly center where you can drop off your kids for an hour or two so you can run some errands.</p>
  </div>
  <%= render 'shared/events' %>
  <%= render 'shared/schedule' %>
</div>